### ISSUE TITLE
申请管理员给出不同的失败提示

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#1]
这种和类似的情况可以给出更精确的提示：
![图片](https://user-images.githubusercontent.com/24679507/130246212-609c1af7-f825-4f33-b5a9-0a3e3917db6a.png)

**Comment by LiXiaoHan0** [comment]
已完善了上图中的和一些我想到的提示语。如果有发现新的可以修改的提示语，欢迎在这里反馈！

**Comment by GJCav** [comment]
okk
