### ISSUE TITLE
把文件上传系统与后端权限系统整合起来

### ISSUE THREAD

**Issue by grw2002** [GJCav/wy-rsv#10]
遥遥无期（bushi

**Comment by GJCav** [comment]
> 
> 
> 遥遥无期（bushi

@grw2002 
其实我想的是这么处理，小程序端加一个按钮“授权网页登录”，然后小程序向后端请求一个简短的口令，把这个口令在网页上输入，向后端请求，后端就把登录的cookie传回网页。然后网页就可以像小程序一样自由使用后端的API了。

**Comment by GJCav** [comment]
目前基本解决了，要改再提新的issue
