### ISSUE TITLE
advice 接口草案

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#11]
要不提建议直接使用github issue??
这样我们就省事了。

功能：接受用户建议。
API：
* POST /advice/ 提交建议
* GET /advice/ 建议列表
* GET /advice/\<advice-id> 获取建议详细信息
* POST /advice/\<advice-id> 修改建议信息（管理员\开发者回复或用户自行修改）

然后一个advice用如下属性描述：
* proponent：提建议的人
* title: 建议标题
* content: 建议主体
* state: 建议状态
* response: 建议答复

**Comment by LiXiaoHan0** [comment]
好正式哦！我一开始都没准备做那么复杂的[doge]

**Comment by GJCav** [comment]
ref #4

**Comment by GJCav** [comment]
已经实现
