### ISSUE TITLE
关于文件上传接口

### ISSUE THREAD

**Issue by LiXiaoHan0** [GJCav/wy-rsv#12]
# 微信小程序本身封装的文件选择与上传接口与服务器现在提供的接口似乎不太一致
## 参考下面的文档和图片<https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/wx.uploadFile.html>
![无标题](https://user-images.githubusercontent.com/86946485/130345382-dd2508cd-2ca2-4f6c-91c9-f9604a608b4d.png)
## 现在使用的上传方式method=‘PUT’
![无标题2](https://user-images.githubusercontent.com/86946485/130345497-38baf23b-ad96-436c-abea-dfc0edd92ca8.png)

**Comment by grw2002** [comment]
我先加一个图片上传接口吧，支持HTTP POST方法

**Comment by LiXiaoHan0** [comment]
> 我先加一个图片上传接口吧，支持HTTP POST方法

多谢了！完成了在docs也里更新一下

**Comment by LiXiaoHan0** [comment]
图片上传和显示已正常实现
