### ISSUE TITLE
添加设备后回到设备列表不显示新添加的设备

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#14]
复现：
1. 进入小程序
2. 进入管理员界面
3. 添加设备
4. 提交
5. 回到设备列表
6. 发现不存在新增加的设备

可能的解决方案：
推荐：每次进入一个页面都重新从服务器拉取数据
替代：或者给用户一个刷新功能。

**Comment by LiXiaoHan0** [comment]
对于改变页面状态的操作均已追加了刷新操作
