### ISSUE TITLE
设备列表中设备名过长导致绘制超出屏幕

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#17]
如此这般：
![图片](https://user-images.githubusercontent.com/24679507/130355643-aeb288cc-4240-4a59-aabc-9ee2645bba5a.png)

修复：
`.server-name`的属性添加如下两行：

```css
word-break: keep-all;
word-wrap: break-word;
```

**Comment by LiXiaoHan0** [comment]
已解决
