### ISSUE TITLE
自由预约返回时间的格式问题

### ISSUE THREAD

**Issue by LiXiaoHan0** [GJCav/wy-rsv#18]
### 提交一个自由预约
![image](https://user-images.githubusercontent.com/86946485/130357426-6973a24b-3dcf-4af4-9907-67669a0222ad.png)
### 最后得到
![无标题](https://user-images.githubusercontent.com/86946485/130357452-6f44e808-4145-4646-ac84-df212983fc77.png)
## 解决方式：
+ 小程序端补足
+ 后端补足

**Comment by GJCav** [comment]
我草，你是不做解析直接放在界面上的？？
我尝试改进一下吧。
