### ISSUE TITLE
提交预约时返回时间冲突问题

### ISSUE THREAD

**Issue by LiXiaoHan0** [GJCav/wy-rsv#19]
###  预约Item1，固定预约，时间为星期二晚上

![image](https://user-images.githubusercontent.com/86946485/130390890-36772066-0bf7-48d5-bcec-0d6fc3ce21ab.png)

### 提交会失败，原因显示时间冲突

![image](https://user-images.githubusercontent.com/86946485/130391039-a4aba35c-bfae-4e3d-af95-fcc8dce8c094.png)

### 但读取到所有预约都已经结束，不应该存在时间冲突

![image](https://user-images.githubusercontent.com/86946485/130391449-590b74f5-7bd3-4610-bb48-5652c9a43523.png)

### 此外预约星期三晚上也会出现同样的问题，不确定错误原因

**Comment by GJCav** [comment]
问题解决了，这个是两方面的问题：
一是后端确实有个bug，判断时间冲突的时候没有更具预约的状态来判断，一些已经被拒绝掉的预约也被加入判断了。
二是因为后端变动比较大，数据库里面的数据不兼容了，现在的版本不能处理一些老的数据，会发生错误，一个典型的例子就是以前预约晚上时间段都是5点开始，所以数据库存的时间是5点，但昨天程序改成了6点，然后程序在处理老数据的时候就傻眼了。

目前两个问题已经修复。
