### ISSUE TITLE
疑似新用户第一次打开后绑定信息控制台提示未登陆

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#2]
复现流程如下：
1. 在服务器数据库上删除用户的所有相关信息：user, admin, admin_req三个表中的用户信息。
2. 停止运行
    ![图片](https://user-images.githubusercontent.com/24679507/130246590-450700bd-d484-4d89-9234-a0bedd0e4aee.png)
2. 清除所有缓存
3. 编译
4. 绑定信息，正常填写，提交
报错如下：
![图片](https://user-images.githubusercontent.com/24679507/130246784-e88ab34e-47d8-498b-b6fa-8501809f7597.png)

但是再次停止运行，编译后行为正常。

**Comment by LiXiaoHan0** [comment]
本地服务器没有试出这个bug，我暂时对这个bug也没啥头绪，也许这只是个偶然事件？
