### ISSUE TITLE
备案完成，API地址更新

### ISSUE THREAD

**Issue by grw2002** [GJCav/wy-rsv#45]
thuwy.top备案完成，所有的API全部迁移到这个域名下，并且全局强制https

- 后端：https://api.thuwy.top/
- 图片端：https://static.thuwy.top/
- **【大改动】图片API**：https://web.thuwy.top/api/
- web端：https://web.thuwy.top/

主要受影响：小程序端、web端

**Comment by LiXiaoHan0** [comment]
网址已更新，部分物品图片失效

**Comment by GJCav** [comment]
似乎已经更新完了。。
