### ISSUE TITLE
未来的某个预约因拒绝或取消结束后对应的时间显示无法预约

### ISSUE THREAD

**Issue by GJCav** [GJCav/wy-rsv#7]
复现：
1. 预约一个时间
2. 取消\管理员拒绝这个预约申请
3. 回到设备列表，点进那个设备的预约界面
4. 发现那一段时间仍然无法预约

原因：
GET /item/<item-id>/reservation/ 接口会**不加筛选**地返回这个物品未来7天的预约信息，即使这个预约因为各种原因被取消掉，但似乎前端并没有对这个进行筛选。

推荐解决方法：
* 后端增强这个借口，让这个借口能像 GET /reservation/ 接口那样支持参数筛选
* 小程序端修改代码，传递给后端的时候加上筛选

**Comment by LiXiaoHan0** [comment]
前端已补充筛选，处于完成状态的预约不会影响新的预约申请
