### ISSUE TITLE
时间系统：统一为时间戳

### ISSUE THREAD

**Issue by grw2002** [GJCav/wy-rsv#9]
## Issue

现在的时间格式是`yyyy-mm-dd [index]`，如果未来要增加任意时间段预约，可扩展性很差

## Solve

统一改为时间戳，即`1970-01-01 00:00:00 GMT`到现在的**毫秒**数（`javascript`中调用`Date.now()`或`new Date().getTime()`获取）

## Remark

1. 时间戳用**毫秒**，并且是`GMT+0`，需要注意时区的设置
2. 至于时间段预约……不要在一个需求上面吊死，既然要求是时间段，那么给时间戳额外加一个验证就好（比如下午时间段必须强制为`13:00-17:00`）。比如`2021-08-21 13:00:00 GMT+8`对应的时间戳为`1629522000000`，虽然这样存储没有很高效地利用信息，但是系统地可扩展性和鲁棒性会增强

**Comment by GJCav** [comment]
@grw2002 
这个不是问题。理由：
数据库内部储存的是时间戳，不存在扩展性问题，但是数据交互使用的是普通字符串。
后端任意时间段预约已经实现，不用修改，接口见：[wiki](https://github.com/GJCav/wy-rsv/blob/master/docs/%E5%90%8E%E7%AB%AFAPI%E4%B8%80%E8%A7%88.md)中提交预约部分。
现阶段只是小程序端还未提供灵活预约功能。

**Comment by grw2002** [comment]
@GJCav 
既然后端已经实现了时间戳存储，那么在中间通讯的过程中全部使用时间戳很容易实现
中间通讯的过程中使用普通字符串鲁棒性可能不太好
